name: Update locale files

on:
  push:
    branches:
      - locale_auto_update


permissions:
  pull-requests: write
  contents: read

jobs:
  locale-updater:
    if: github.repository == 'dpgraham4401/djangorestframework-simplejwt'
    name: Locale updater
    runs-on: ubuntu-latest
    steps:

    - name: Checkout Repository
      uses: actions/checkout@v4

#    - name: Checkout PR
#      env:
#        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#      run: gh pr checkout ${{ github.event.pull_request.number }}

    - name: Set up Python 3.9
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
        cache: 'pip'
        cache-dependency-path: setup.py

    - name: Install dependencies
      run: |
        sudo apt-get install -y gettext 
        python -m pip install --upgrade pip wheel setuptools
        pip install -e .[dev]

    - name: Run locale Update Script
      working-directory: rest_framework_simplejwt
      run: |
        python ../scripts/i18n_updater.py

#    - name: Save PR number
#      run: |
#        mkdir -p ./pr
#        echo "${{ github.event.number }}" > ./pr/NR
#
#    - name: Upload PR number
#      uses: actions/upload-artifact@v4
#      with:
#        name: pr
#        path: ./pr
#        overwrite: true

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v6
      id: auto-commit-action
      with:
        branch: i18n-auto-update
        title: "[i18n] Update"
        body: "Updated locale files on master branch"
        commit-message: "Update locale files"
        add-paths: rest_framework_simplejwt/locale/**

